version: '3.8'
services:

  pitstop-api1:
    image: kauajuhrs/pitstop-api:latest
    restart: always
    ports:
      - "8081:8080"

  pitstop-api2:
    image: kauajuhrs/pitstop-api:latest
    restart: always
    ports:
      - "8082:8080"

  nginx-lb:
    image: kauajuhrs/nginx-lb:latest
    restart: always
    ports:
      - "80:80"
