version: '3.8'
services:

  buscar-api1:
    image: kauajuhrs/buscar-api:latest
    restart: always
    ports:
      - "8081:8080"

  buscar-api2:
    image: kauajuhrs/buscar-api:latest
    restart: always
    ports:
      - "8082:8080"

  nginx-lb:
    image: kauajuhrs/nginx-lb:latest
    restart: always
    ports:
      - "80:80"
